spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientdb}
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO

t1:
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: client-processing
      max.poll.records: 10
      session-timeout: 10000
      heartbeat.interval: 3000
    producer:
      enable: true
    topic:
      client_products: client_products
      client_credit_products: client_credit_products
      client_cards: client_cards
      service_logs: service_logs
    listener:
      poll-timeout: 1000
  service:
    name: client-processing
  metric:
    limit-ms: 500
  cache:
    ttl-ms: 60000
security:
  token: dGhpcy1pcy1hLWxvbmc2NGJhc2Utc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmctZm9yLWRlbW8=
  expiration: 86400000